// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingSpotsManager.Shared.Database;

namespace ParkingSpotsManager.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("ParkingSpotsManager.Shared.Models.Parking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Columns");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int?>("Rows");

                    b.HasKey("Id");

                    b.ToTable("Parkings");
                });

            modelBuilder.Entity("ParkingSpotsManager.Shared.Models.Spot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime?>("OccupiedAt");

                    b.Property<int?>("OccupiedBy");

                    b.Property<int>("ParkingId");

                    b.Property<DateTime?>("ReleasedAt");

                    b.HasKey("Id");

                    b.HasIndex("ParkingId");

                    b.ToTable("Spots");
                });

            modelBuilder.Entity("ParkingSpotsManager.Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthToken");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Firstname");

                    b.Property<string>("Lastname");

                    b.Property<int?>("ParkingId");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("ParkingId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ParkingSpotsManager.Shared.Models.UserParking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IsAdmin");

                    b.Property<int>("ParkingId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UsersParkings");
                });

            modelBuilder.Entity("ParkingSpotsManager.Shared.Models.Spot", b =>
                {
                    b.HasOne("ParkingSpotsManager.Shared.Models.Parking", "Parking")
                        .WithMany("Spots")
                        .HasForeignKey("ParkingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ParkingSpotsManager.Shared.Models.User", b =>
                {
                    b.HasOne("ParkingSpotsManager.Shared.Models.Parking")
                        .WithMany("Users")
                        .HasForeignKey("ParkingId");
                });
#pragma warning restore 612, 618
        }
    }
}
